{{- if .Values.gcloudServiceAccount }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcloud-service-account
data:
  credentials.json:   {{ .Values.gcloudServiceAccount | b64enc | quote }}
{{- end }}
