apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings
data:
  settings.yml: |-
    github_organization: {{ .Values.githubOrganization }}
    cloud_nine_region: {{ .Values.cloudNineRegion }}
    cloud_nine_tenant: {{ .Values.cloudNineTenant }}
    python_config: {{ .Values.pythonConfigModule }}
    runner_pool:
{{ .Values.runnerPool | toYaml | indent 6 }}
    extra_runner_timer:
{{ .Values.extraRunnerTimer | toYaml | indent 6 }}
