version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - /bin/bash
    volumes:
      - "./srcs:/app/srcs"
      - "./templates:/app/templates"
      - ./test_settings.yml:/app/test_settings.yml
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/application_default_credentials.json
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONIOENCODING=UTF-8
      - SETTING_FILE=/app/test_settings.yml
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
