{{- if .Values.gcloudServiceAccount }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcloud-service-account
data:
  # The base64 encoded json file which contains the key
  credentials.json: {{ .Values.gcloudServiceAccount | b64enc }}
{{- end }}
