apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  GITHUB_TOKEN:   {{ .Values.githubToken | b64enc }}
  REDHAT_USERNAME: {{ .Values.redhatUsername | b64enc }}
  REDHAT_PASSWORD: {{ .Values.redhatPassword | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretKey | b64enc }}
  {{- if .Values.awsSessionToken }}
    AWS_SESSION_TOKEN: {{ .Values.awsSessionToken | b64enc }}
  {{- end }}
